-- AidJobs Sample Data
-- Seed data for testing and development

-- Insert sample sources (job boards to crawl)
INSERT INTO sources (org_name, careers_url, source_type, status, crawl_frequency_days, last_crawl_status)
VALUES
    ('United Nations Development Programme', 'https://careers.undp.org/cj_api/jobs', 'json', 'active', 1, 'success'),
    ('Médecins Sans Frontières', 'https://www.msf.org/careers', 'html', 'active', 2, 'success'),
    ('Global Partnership for Education', 'https://www.globalpartnership.org/careers', 'html', 'pending_validation', 3, NULL)
ON CONFLICT DO NOTHING;

-- Insert sample jobs
INSERT INTO jobs (
    source_id,
    org_name,
    title,
    location_raw,
    country,
    country_iso,
    city,
    level_norm,
    mission_tags,
    international_eligible,
    deadline,
    apply_url,
    description_snippet,
    canonical_hash,
    status
)
VALUES
    (
        (SELECT id FROM sources WHERE org_name = 'United Nations Development Programme' LIMIT 1),
        'UNDP',
        'Project Coordinator - Climate Change Adaptation',
        'Nairobi, Kenya',
        'Kenya',
        'KE',
        'Nairobi',
        'mid',
        ARRAY['environment', 'development'],
        true,
        CURRENT_DATE + INTERVAL '21 days',
        'https://careers.undp.org/job/12345',
        'Lead climate adaptation projects in East Africa region. Manage team of 8-10 professionals. MSc in Environmental Science required.',
        'undp-climate-coord-nairobi-2024-001',
        'active'
    ),
    (
        (SELECT id FROM sources WHERE org_name = 'United Nations Development Programme' LIMIT 1),
        'UNDP',
        'Senior Programme Officer - Gender Equality',
        'New York, USA',
        'United States',
        'US',
        'New York',
        'senior',
        ARRAY['human-rights', 'development'],
        true,
        CURRENT_DATE + INTERVAL '14 days',
        'https://careers.undp.org/job/12346',
        'Design and implement gender equality programmes. 10+ years experience in international development.',
        'undp-gender-officer-ny-2024-002',
        'active'
    ),
    (
        (SELECT id FROM sources WHERE org_name = 'Médecins Sans Frontières' LIMIT 1),
        'MSF',
        'Emergency Medical Coordinator',
        'South Sudan',
        'South Sudan',
        'SS',
        NULL,
        'senior',
        ARRAY['health', 'human-rights'],
        true,
        CURRENT_DATE + INTERVAL '10 days',
        'https://www.msf.org/careers/emergency-med-coord-ss',
        'Coordinate emergency medical response in conflict zones. MD required with emergency medicine specialization.',
        'msf-emergency-coord-ss-2024-003',
        'active'
    ),
    (
        (SELECT id FROM sources WHERE org_name = 'Médecins Sans Frontières' LIMIT 1),
        'MSF',
        'Nurse - Maternal Health',
        'Kampala, Uganda',
        'Uganda',
        'UG',
        'Kampala',
        'mid',
        ARRAY['health'],
        false,
        CURRENT_DATE + INTERVAL '30 days',
        'https://www.msf.org/careers/nurse-maternal-ug',
        'Provide maternal healthcare in refugee settlement. Registered nurse with midwifery certification.',
        'msf-nurse-maternal-ug-2024-004',
        'active'
    ),
    (
        (SELECT id FROM sources WHERE org_name = 'Médecins Sans Frontières' LIMIT 1),
        'MSF',
        'Logistics Officer',
        'Addis Ababa, Ethiopia',
        'Ethiopia',
        'ET',
        'Addis Ababa',
        'entry',
        ARRAY['development'],
        false,
        CURRENT_DATE + INTERVAL '45 days',
        'https://www.msf.org/careers/logistics-officer-et',
        'Support supply chain operations for medical missions. Bachelor degree in logistics or related field.',
        'msf-logistics-et-2024-005',
        'active'
    ),
    (
        (SELECT id FROM sources WHERE org_name = 'Global Partnership for Education' LIMIT 1),
        'GPE',
        'Education Policy Analyst',
        'Dar es Salaam, Tanzania',
        'Tanzania',
        'TZ',
        'Dar es Salaam',
        'mid',
        ARRAY['education', 'development'],
        false,
        CURRENT_DATE + INTERVAL '28 days',
        'https://www.globalpartnership.org/careers/policy-analyst-tz',
        'Analyze education policies and advise government partners. Masters in Education Policy or Public Policy.',
        'gpe-policy-analyst-tz-2024-006',
        'active'
    ),
    (
        (SELECT id FROM sources WHERE org_name = 'Global Partnership for Education' LIMIT 1),
        'GPE',
        'Senior Education Specialist',
        'Remote - Africa Region',
        NULL,
        NULL,
        NULL,
        'senior',
        ARRAY['education'],
        true,
        CURRENT_DATE + INTERVAL '20 days',
        'https://www.globalpartnership.org/careers/senior-specialist',
        'Lead education system strengthening initiatives across Sub-Saharan Africa. PhD preferred, 15+ years experience.',
        'gpe-senior-specialist-africa-2024-007',
        'active'
    ),
    (
        (SELECT id FROM sources WHERE org_name = 'United Nations Development Programme' LIMIT 1),
        'UNDP',
        'Communications Associate',
        'Cape Town, South Africa',
        'South Africa',
        'ZA',
        'Cape Town',
        'entry',
        ARRAY['development'],
        false,
        CURRENT_DATE + INTERVAL '35 days',
        'https://careers.undp.org/job/12347',
        'Support communications and outreach activities. Bachelor degree in Communications or Journalism.',
        'undp-comms-associate-za-2024-008',
        'active'
    ),
    (
        (SELECT id FROM sources WHERE org_name = 'Médecins Sans Frontières' LIMIT 1),
        'MSF',
        'Field HR Manager',
        'Multiple Locations - East Africa',
        NULL,
        NULL,
        NULL,
        'mid',
        ARRAY['human-rights', 'development'],
        true,
        CURRENT_DATE + INTERVAL '25 days',
        'https://www.msf.org/careers/field-hr-manager',
        'Manage HR operations across multiple field missions. 5+ years HR experience in humanitarian context.',
        'msf-hr-manager-ea-2024-009',
        'active'
    ),
    (
        (SELECT id FROM sources WHERE org_name = 'Global Partnership for Education' LIMIT 1),
        'GPE',
        'Monitoring & Evaluation Officer',
        'Nairobi, Kenya',
        'Kenya',
        'KE',
        'Nairobi',
        'mid',
        ARRAY['education', 'development'],
        false,
        CURRENT_DATE + INTERVAL '18 days',
        'https://www.globalpartnership.org/careers/me-officer-ke',
        'Design and implement M&E frameworks for education programs. Strong statistical analysis skills required.',
        'gpe-me-officer-ke-2024-010',
        'active'
    ),
    (
        (SELECT id FROM sources WHERE org_name = 'United Nations Development Programme' LIMIT 1),
        'UNDP',
        'Data Analyst - SDG Reporting',
        'Geneva, Switzerland',
        'Switzerland',
        'CH',
        'Geneva',
        'entry',
        ARRAY['development'],
        true,
        CURRENT_DATE + INTERVAL '40 days',
        'https://careers.undp.org/job/12348',
        'Analyze SDG progress data and produce reports. Proficiency in Python, R, or similar tools.',
        'undp-data-analyst-ch-2024-011',
        'active'
    ),
    (
        (SELECT id FROM sources WHERE org_name = 'Médecins Sans Frontières' LIMIT 1),
        'MSF',
        'Mental Health Specialist',
        'Cox Bazar, Bangladesh',
        'Bangladesh',
        'BD',
        'Cox Bazar',
        'senior',
        ARRAY['health', 'human-rights'],
        true,
        CURRENT_DATE + INTERVAL '15 days',
        'https://www.msf.org/careers/mental-health-bd',
        'Provide mental health services in refugee camps. Clinical psychologist with trauma specialization.',
        'msf-mental-health-bd-2024-012',
        'active'
    )
ON CONFLICT (canonical_hash) DO NOTHING;
